app.url=https://accorhotels-test.coupahost.com

app.username=TEMP-AELHA
app.password=Clavier@123
app.username.display=Anas ELHASSANI


timeout.implicit=5
timeout.explicit=15
timeout.page.load=30

browser=chrome
headless=false

report.folder=test-output/reports

app.url=https://accorhotels-test.coupahost.com

e2e.requisition.description=Requests using CGI france
e2e.requisition.description2=Second item in the DA
e2e.requisition.supplier=CGI FRANCE
e2e.requisition.commodity=N020101
e2e.requisition.unitprice=25
e2e.requisition.quantity=2
e2e.requisition.title=Requisition for Items
e2e.requisition.comment=Requisition is filled correctly
e2e.requisition.supplierPartNumber=433

e2e.attachment.path=C:\\Users\\anas.elhassani\\Downloads\\TEST.pdf

e2e.approver1=KARIM SANKHON
e2e.approver2=Guillaume TAP
e2e.approver3=CYRIL PLANCHE

e2e.invoice.user=CORALIE MANIOU
e2e.invoice.number=9005
